/**
 * @fileoverview This file is generated by the Angular template compiler.
 * Do not edit.
 * @suppress {suspiciousCode,uselessCode,missingProperties,missingOverride}
 */
 /* tslint:disable */


import * as i0 from '@angular/core';
import * as i1 from './app.module';
import * as i2 from './app.component';
import * as i3 from '../../../../../node_modules/@angular-mdl/core/components/dialog-outlet/mdl-dialog-outlet.component.ngfactory';
import * as i4 from '../../../../../node_modules/@angular-mdl/core/components/dialog-outlet/mdl-backdrop-overlay.component.ngfactory';
import * as i5 from '../../../../../node_modules/@angular-mdl/core/components/dialog/mdl-dialog.component.ngfactory';
import * as i6 from '../../../../../node_modules/@angular-mdl/core/components/dialog/mdl-alert.component.ngfactory';
import * as i7 from '../../../../../node_modules/@angular-mdl/core/components/dialog/mdl-dialog-host.component.ngfactory';
import * as i8 from '../../../../../node_modules/@angular-mdl/core/components/dialog/mdl-simple-dialog.component.ngfactory';
import * as i9 from '../../../../../node_modules/@angular-mdl/core/components/snackbar/mdl-snackbar.service.ngfactory';
import * as i10 from '../../../../../node_modules/@angular-mdl/core/components/tooltip/mdl-tooltip.component.ngfactory';
import * as i11 from './dashboard.component.ngfactory';
import * as i12 from './shucedule.component.ngfactory';
import * as i13 from './app.component.ngfactory';
import * as i14 from '@angular/common';
import * as i15 from '@angular/platform-browser';
import * as i16 from '@angular/forms';
import * as i17 from '@angular/http';
import * as i18 from '@angular-mdl/core/components/common/animations';
import * as i19 from '@angular-mdl/core/components/common/index';
import * as i20 from '@angular-mdl/core/components/dialog-outlet/mdl-dialog-outlet.service';
import * as i21 from '@angular-mdl/core/components/layout/mdl-layout.component';
import * as i22 from '@angular-mdl/core/components/dialog/mdl-dialog.service';
import * as i23 from '@angular-mdl/core/components/radio/mdl-radio.component';
import * as i24 from '@angular-mdl/core/components/snackbar/mdl-snackbar.service';
import * as i25 from '@angular-mdl/core/components/menu/mdl-menu.component';
import * as i26 from '@angular/router';
import * as i27 from './socketio.service';
import * as i28 from './shucedule.service';
import * as i29 from './reserve.service';
import * as i30 from '@angular-mdl/core/components/button/mdl-button.component';
import * as i31 from '@angular-mdl/core/components/icon/mdl-icon.component';
import * as i32 from '@angular-mdl/core/components/common/mdl-ripple.directive';
import * as i33 from '@angular-mdl/core/components/tabs/index';
import * as i34 from '@angular-mdl/core/components/layout/index';
import * as i35 from '@angular-mdl/core/components/checkbox/mdl-checkbox.component';
import * as i36 from '@angular-mdl/core/components/chips/index';
import * as i37 from '@angular-mdl/core/components/dialog-outlet/index';
import * as i38 from '@angular-mdl/core/components/dialog/index';
import * as i39 from '@angular-mdl/core/components/spinner/mdl-spinner.component';
import * as i40 from '@angular-mdl/core/components/badge/mdl-badge.directive';
import * as i41 from '@angular-mdl/core/components/shadow/mdl-shadow.directive';
import * as i42 from '@angular-mdl/core/components/card/mdl-card.component';
import * as i43 from '@angular-mdl/core/components/progress/mdl-progress.component';
import * as i44 from '@angular-mdl/core/components/icon-toggle/mdl-icon-toggle.component';
import * as i45 from '@angular-mdl/core/components/list/mdl-list.component';
import * as i46 from '@angular-mdl/core/components/slider/mdl-slider.component';
import * as i47 from '@angular-mdl/core/components/switch/mdl-switch.component';
import * as i48 from '@angular-mdl/core/components/tooltip/index';
import * as i49 from '@angular-mdl/core/components/table/index';
import * as i50 from '@angular-mdl/core/components/menu/index';
import * as i51 from '@angular-mdl/core/components/textfield/mdl-textfield.component';
import * as i52 from '@angular-mdl/core/components/index';
import * as i53 from './dashboard.component';
import * as i54 from './shucedule.component';
import * as i55 from './app-routing.module';
export const AppModuleNgFactory:i0.NgModuleFactory<i1.AppModule> = i0.ɵcmf(i1.AppModule,
    [i2.AppComponent],(_l:any) => {
      return i0.ɵmod([i0.ɵmpd(512,i0.ComponentFactoryResolver,i0.ɵCodegenComponentFactoryResolver,
          [[8,[i3.MdlDialogOutletComponentNgFactory,i4.MdlBackdropOverlayComponentNgFactory,
              i5.MdlDialogComponentNgFactory,i6.MdlAlertComponentNgFactory,i7.MdlDialogHostComponentNgFactory,
              i8.MdlSimpleDialogComponentNgFactory,i9.MdlSnackbarComponentNgFactory,
              i10.MdlSimpleTooltipComponentNgFactory,i11.DashboardComponentNgFactory,
              i12.ShuceduleComponentNgFactory,i13.AppComponentNgFactory]],[3,i0.ComponentFactoryResolver],
              i0.NgModuleRef]),i0.ɵmpd(5120,i0.LOCALE_ID,i0.ɵm,[[3,i0.LOCALE_ID]]),
          i0.ɵmpd(4608,i14.NgLocalization,i14.NgLocaleLocalization,[i0.LOCALE_ID]),
          i0.ɵmpd(5120,i0.APP_ID,i0.ɵf,([] as any[])),i0.ɵmpd(5120,i0.IterableDiffers,
              i0.ɵk,([] as any[])),i0.ɵmpd(5120,i0.KeyValueDiffers,i0.ɵl,([] as any[])),
          i0.ɵmpd(4608,i15.DomSanitizer,i15.ɵe,[i14.DOCUMENT]),i0.ɵmpd(6144,i0.Sanitizer,
              (null as any),[i15.DomSanitizer]),i0.ɵmpd(4608,i15.HAMMER_GESTURE_CONFIG,
              i15.HammerGestureConfig,([] as any[])),i0.ɵmpd(5120,i15.EVENT_MANAGER_PLUGINS,
              (p0_0:any,p1_0:any,p2_0:any,p2_1:any) => {
                return [new i15.ɵDomEventsPlugin(p0_0),new i15.ɵKeyEventsPlugin(p1_0),
                    new i15.ɵHammerGesturesPlugin(p2_0,p2_1)];
              },[i14.DOCUMENT,i14.DOCUMENT,i14.DOCUMENT,i15.HAMMER_GESTURE_CONFIG]),
          i0.ɵmpd(4608,i15.EventManager,i15.EventManager,[i15.EVENT_MANAGER_PLUGINS,
              i0.NgZone]),i0.ɵmpd(135680,i15.ɵDomSharedStylesHost,i15.ɵDomSharedStylesHost,
              [i14.DOCUMENT]),i0.ɵmpd(4608,i15.ɵDomRendererFactory2,i15.ɵDomRendererFactory2,
              [i15.EventManager,i15.ɵDomSharedStylesHost]),i0.ɵmpd(6144,i0.RendererFactory2,
              (null as any),[i15.ɵDomRendererFactory2]),i0.ɵmpd(6144,i15.ɵSharedStylesHost,
              (null as any),[i15.ɵDomSharedStylesHost]),i0.ɵmpd(4608,i0.Testability,
              i0.Testability,[i0.NgZone]),i0.ɵmpd(4608,i15.Meta,i15.Meta,[i14.DOCUMENT]),
          i0.ɵmpd(4608,i15.Title,i15.Title,[i14.DOCUMENT]),i0.ɵmpd(4608,i16.ɵi,i16.ɵi,
              ([] as any[])),i0.ɵmpd(4608,i17.BrowserXhr,i17.BrowserXhr,([] as any[])),
          i0.ɵmpd(4608,i17.ResponseOptions,i17.BaseResponseOptions,([] as any[])),
          i0.ɵmpd(5120,i17.XSRFStrategy,i17.ɵb,([] as any[])),i0.ɵmpd(4608,i17.XHRBackend,
              i17.XHRBackend,[i17.BrowserXhr,i17.ResponseOptions,i17.XSRFStrategy]),
          i0.ɵmpd(4608,i17.RequestOptions,i17.BaseRequestOptions,([] as any[])),i0.ɵmpd(5120,
              i17.Http,i17.ɵc,[i17.XHRBackend,i17.RequestOptions]),i0.ɵmpd(5120,i18.Animations,
              i19.instantiateSupportedAnimationDriver,([] as any[])),i0.ɵmpd(4608,
              i20.MdlDialogOutletService,i20.MdlDialogOutletService,[i0.ApplicationRef,
                  i0.ComponentFactoryResolver]),i0.ɵmpd(4608,i21.MdlScreenSizeService,
              i21.MdlScreenSizeService,[i0.NgZone,[2,i21.LAYOUT_SCREEN_SIZE_THRESHOLD]]),
          i0.ɵmpd(4608,i22.MdlDialogService,i22.MdlDialogService,[i0.ComponentFactoryResolver,
              i15.DOCUMENT,i0.ApplicationRef,i20.MdlDialogOutletService]),i0.ɵmpd(4608,
              i23.MdlRadioGroupRegisty,i23.MdlRadioGroupRegisty,([] as any[])),i0.ɵmpd(4608,
              i24.MdlSnackbarService,i24.MdlSnackbarService,[i0.ComponentFactoryResolver,
                  i20.MdlDialogOutletService]),i0.ɵmpd(4608,i25.MdlMenuRegisty,i25.MdlMenuRegisty,
              ([] as any[])),i0.ɵmpd(5120,i26.ActivatedRoute,i26.ɵf,[i26.Router]),
          i0.ɵmpd(4608,i26.NoPreloading,i26.NoPreloading,([] as any[])),i0.ɵmpd(6144,
              i26.PreloadingStrategy,(null as any),[i26.NoPreloading]),i0.ɵmpd(135680,
              i26.RouterPreloader,i26.RouterPreloader,[i26.Router,i0.NgModuleFactoryLoader,
                  i0.Compiler,i0.Injector,i26.PreloadingStrategy]),i0.ɵmpd(4608,i26.PreloadAllModules,
              i26.PreloadAllModules,([] as any[])),i0.ɵmpd(5120,i26.ROUTER_INITIALIZER,
              i26.ɵi,[i26.ɵg]),i0.ɵmpd(5120,i0.APP_BOOTSTRAP_LISTENER,(p0_0:any) => {
            return [p0_0];
          },[i26.ROUTER_INITIALIZER]),i0.ɵmpd(4608,i27.SocketIOService,i27.SocketIOService,
              ([] as any[])),i0.ɵmpd(4608,i28.ShuceduleService,i28.ShuceduleService,
              [i17.Http,i27.SocketIOService]),i0.ɵmpd(4608,i29.ReserveService,i29.ReserveService,
              [i17.Http,i27.SocketIOService]),i0.ɵmpd(512,i14.CommonModule,i14.CommonModule,
              ([] as any[])),i0.ɵmpd(1024,i0.ErrorHandler,i15.ɵa,([] as any[])),i0.ɵmpd(1024,
              i0.NgProbeToken,() => {
                return [i26.ɵb()];
              },([] as any[])),i0.ɵmpd(512,i26.ɵg,i26.ɵg,[i0.Injector]),i0.ɵmpd(1024,
              i0.APP_INITIALIZER,(p0_0:any,p0_1:any,p1_0:any) => {
                return [i15.ɵc(p0_0,p0_1),i26.ɵh(p1_0)];
              },[[2,i15.NgProbeToken],[2,i0.NgProbeToken],i26.ɵg]),i0.ɵmpd(512,i0.ApplicationInitStatus,
              i0.ApplicationInitStatus,[[2,i0.APP_INITIALIZER]]),i0.ɵmpd(131584,i0.ɵe,
              i0.ɵe,[i0.NgZone,i0.ɵConsole,i0.Injector,i0.ErrorHandler,i0.ComponentFactoryResolver,
                  i0.ApplicationInitStatus]),i0.ɵmpd(2048,i0.ApplicationRef,(null as any),
              [i0.ɵe]),i0.ɵmpd(512,i0.ApplicationModule,i0.ApplicationModule,[i0.ApplicationRef]),
          i0.ɵmpd(512,i15.BrowserModule,i15.BrowserModule,[[3,i15.BrowserModule]]),
          i0.ɵmpd(512,i16.ɵba,i16.ɵba,([] as any[])),i0.ɵmpd(512,i16.FormsModule,i16.FormsModule,
              ([] as any[])),i0.ɵmpd(512,i17.HttpModule,i17.HttpModule,([] as any[])),
          i0.ɵmpd(512,i30.MdlButtonModule,i30.MdlButtonModule,([] as any[])),i0.ɵmpd(512,
              i31.MdlIconModule,i31.MdlIconModule,([] as any[])),i0.ɵmpd(512,i32.MdlRippleModule,
              i32.MdlRippleModule,([] as any[])),i0.ɵmpd(512,i19.MdlCommonsModule,
              i19.MdlCommonsModule,([] as any[])),i0.ɵmpd(512,i33.MdlTabsModule,i33.MdlTabsModule,
              ([] as any[])),i0.ɵmpd(512,i34.MdlLayoutModule,i34.MdlLayoutModule,([] as any[])),
          i0.ɵmpd(512,i35.MdlCheckboxModule,i35.MdlCheckboxModule,([] as any[])),i0.ɵmpd(512,
              i36.MdlChipModule,i36.MdlChipModule,([] as any[])),i0.ɵmpd(512,i37.MdlDialogOutletModule,
              i37.MdlDialogOutletModule,([] as any[])),i0.ɵmpd(512,i38.MdlDialogModule,
              i38.MdlDialogModule,([] as any[])),i0.ɵmpd(512,i39.MdlSpinnerModule,
              i39.MdlSpinnerModule,([] as any[])),i0.ɵmpd(512,i40.MdlBadgeModule,i40.MdlBadgeModule,
              ([] as any[])),i0.ɵmpd(512,i41.MdlShadowModule,i41.MdlShadowModule,([] as any[])),
          i0.ɵmpd(512,i42.MdlCardModule,i42.MdlCardModule,([] as any[])),i0.ɵmpd(512,
              i23.MdlRadioModule,i23.MdlRadioModule,([] as any[])),i0.ɵmpd(512,i43.MdlProgressModule,
              i43.MdlProgressModule,([] as any[])),i0.ɵmpd(512,i44.MdlIconToggleModule,
              i44.MdlIconToggleModule,([] as any[])),i0.ɵmpd(512,i45.MdlListModule,
              i45.MdlListModule,([] as any[])),i0.ɵmpd(512,i46.MdlSliderModule,i46.MdlSliderModule,
              ([] as any[])),i0.ɵmpd(512,i47.MdlSwitchModule,i47.MdlSwitchModule,([] as any[])),
          i0.ɵmpd(512,i24.MdlSnackbaModule,i24.MdlSnackbaModule,([] as any[])),i0.ɵmpd(512,
              i48.MdlTooltipModule,i48.MdlTooltipModule,([] as any[])),i0.ɵmpd(512,
              i49.MdlTableModule,i49.MdlTableModule,([] as any[])),i0.ɵmpd(512,i50.MdlMenuModule,
              i50.MdlMenuModule,([] as any[])),i0.ɵmpd(512,i51.MdlTextFieldModule,
              i51.MdlTextFieldModule,([] as any[])),i0.ɵmpd(512,i52.MdlModule,i52.MdlModule,
              ([] as any[])),i0.ɵmpd(1024,i26.ɵa,i26.ɵd,[[3,i26.Router]]),i0.ɵmpd(512,
              i26.UrlSerializer,i26.DefaultUrlSerializer,([] as any[])),i0.ɵmpd(512,
              i26.ChildrenOutletContexts,i26.ChildrenOutletContexts,([] as any[])),
          i0.ɵmpd(256,i26.ROUTER_CONFIGURATION,{},([] as any[])),i0.ɵmpd(1024,i14.LocationStrategy,
              i26.ɵc,[i14.PlatformLocation,[2,i14.APP_BASE_HREF],i26.ROUTER_CONFIGURATION]),
          i0.ɵmpd(512,i14.Location,i14.Location,[i14.LocationStrategy]),i0.ɵmpd(512,
              i0.Compiler,i0.Compiler,([] as any[])),i0.ɵmpd(512,i0.NgModuleFactoryLoader,
              i0.SystemJsNgModuleLoader,[i0.Compiler,[2,i0.SystemJsNgModuleLoaderConfig]]),
          i0.ɵmpd(1024,i26.ROUTES,() => {
            return [[{path:'',redirectTo:'/dashboard',pathMatch:'full'},{path:'dashboard',
                component:i53.DashboardComponent},{path:'shucedule',component:i54.ShuceduleComponent}]];
          },([] as any[])),i0.ɵmpd(1024,i26.Router,i26.ɵe,[i0.ApplicationRef,i26.UrlSerializer,
              i26.ChildrenOutletContexts,i14.Location,i0.Injector,i0.NgModuleFactoryLoader,
              i0.Compiler,i26.ROUTES,i26.ROUTER_CONFIGURATION,[2,i26.UrlHandlingStrategy],
              [2,i26.RouteReuseStrategy]]),i0.ɵmpd(512,i26.RouterModule,i26.RouterModule,
              [[2,i26.ɵa],[2,i26.Router]]),i0.ɵmpd(512,i55.AppRoutingModule,i55.AppRoutingModule,
              ([] as any[])),i0.ɵmpd(512,i1.AppModule,i1.AppModule,([] as any[]))]);
    });
//# sourceMappingURL=data:application/json;base64,eyJmaWxlIjoiRDovcHJvZ3JhbS9BbXVtdS9saWIvY2hpbmFjaHUvcHJveHkvd2ViX21hdGVyaWFsL2FwcC9hcHAubW9kdWxlLm5nZmFjdG9yeS50cyIsInZlcnNpb24iOjMsInNvdXJjZVJvb3QiOiIiLCJzb3VyY2VzIjpbIm5nOi8vL0Q6L3Byb2dyYW0vQW11bXUvbGliL2NoaW5hY2h1L3Byb3h5L3dlYl9tYXRlcmlhbC9hcHAvYXBwLm1vZHVsZS50cyJdLCJzb3VyY2VzQ29udGVudCI6WyIgIl0sIm1hcHBpbmdzIjoiQUFBQTs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7OyJ9
