/**
 * @fileoverview This file is generated by the Angular template compiler.
 * Do not edit.
 * @suppress {suspiciousCode,uselessCode,missingProperties,missingOverride}
 */
 /* tslint:disable */


import * as i0 from './dashboard.component.css.shim.ngstyle';
import * as i1 from '@angular/core';
import * as i2 from './reservelist.component.ngfactory';
import * as i3 from './reservelist.component';
import * as i4 from './reserve.service';
import * as i5 from './dashboard.component';
const styles_DashboardComponent:any[] = [i0.styles];
export const RenderType_DashboardComponent:i1.RendererType2 = i1.ɵcrt({encapsulation:0,
    styles:styles_DashboardComponent,data:{}});
export function View_DashboardComponent_0(_l:any):i1.ɵViewDefinition {
  return i1.ɵvid(0,[(_l()(),i1.ɵeld(0,(null as any),(null as any),1,'h3',([] as any[]),
      (null as any),(null as any),(null as any),(null as any),(null as any))),(_l()(),
      i1.ɵted((null as any),['Dashboard'])),(_l()(),i1.ɵted((null as any),['\n'])),
      (_l()(),i1.ɵeld(0,(null as any),(null as any),4,'div',[['class','grid grid-pad']],
          (null as any),(null as any),(null as any),(null as any),(null as any))),
      (_l()(),i1.ɵted((null as any),['\n  '])),(_l()(),i1.ɵeld(0,(null as any),(null as any),
          1,'reserve-list',([] as any[]),(null as any),(null as any),(null as any),
          i2.View_ReserveListComponent_0,i2.RenderType_ReserveListComponent)),i1.ɵdid(114688,
          (null as any),0,i3.ReserveListComponent,[i4.ReserveService],(null as any),
          (null as any)),(_l()(),i1.ɵted((null as any),['\n'])),(_l()(),i1.ɵted((null as any),
          ['\n']))],(_ck,_v) => {
    _ck(_v,6,0);
  },(null as any));
}
export function View_DashboardComponent_Host_0(_l:any):i1.ɵViewDefinition {
  return i1.ɵvid(0,[(_l()(),i1.ɵeld(0,(null as any),(null as any),1,'amumu-dashboard',
      ([] as any[]),(null as any),(null as any),(null as any),View_DashboardComponent_0,
      RenderType_DashboardComponent)),i1.ɵdid(114688,(null as any),0,i5.DashboardComponent,
      ([] as any[]),(null as any),(null as any))],(_ck,_v) => {
    _ck(_v,1,0);
  },(null as any));
}
export const DashboardComponentNgFactory:i1.ComponentFactory<i5.DashboardComponent> = i1.ɵccf('amumu-dashboard',
    i5.DashboardComponent,View_DashboardComponent_Host_0,{},{},([] as any[]));
//# sourceMappingURL=data:application/json;base64,eyJmaWxlIjoiRDovcHJvZ3JhbS9BbXVtdS9saWIvY2hpbmFjaHUvcHJveHkvd2ViX21hdGVyaWFsL2FwcC9kYXNoYm9hcmQuY29tcG9uZW50Lm5nZmFjdG9yeS50cyIsInZlcnNpb24iOjMsInNvdXJjZVJvb3QiOiIiLCJzb3VyY2VzIjpbIm5nOi8vL0Q6L3Byb2dyYW0vQW11bXUvbGliL2NoaW5hY2h1L3Byb3h5L3dlYl9tYXRlcmlhbC9hcHAvZGFzaGJvYXJkLmNvbXBvbmVudC50cyIsIm5nOi8vL0Q6L3Byb2dyYW0vQW11bXUvbGliL2NoaW5hY2h1L3Byb3h5L3dlYl9tYXRlcmlhbC9hcHAvZGFzaGJvYXJkLmNvbXBvbmVudC5odG1sIiwibmc6Ly8vRDovcHJvZ3JhbS9BbXVtdS9saWIvY2hpbmFjaHUvcHJveHkvd2ViX21hdGVyaWFsL2FwcC9kYXNoYm9hcmQuY29tcG9uZW50LnRzLkRhc2hib2FyZENvbXBvbmVudF9Ib3N0Lmh0bWwiXSwic291cmNlc0NvbnRlbnQiOlsiICIsIjxoMz5EYXNoYm9hcmQ8L2gzPlxuPGRpdiBjbGFzcz1cImdyaWQgZ3JpZC1wYWRcIj5cbiAgPHJlc2VydmUtbGlzdD48L3Jlc2VydmUtbGlzdD5cbjwvZGl2PlxuIiwiPGFtdW11LWRhc2hib2FyZD48L2FtdW11LWRhc2hib2FyZD4iXSwibWFwcGluZ3MiOiJBQUFBOzs7Ozs7Ozs7Ozs7Ozs7Ozs7b0JDQUE7TUFBQSx3RUFBSTthQUFBLCtCQUFjO01BQ2xCO1VBQUE7TUFBMkIseUNBQ3pCO1VBQUE7MkVBQUEsVUFBQTtVQUFBO1VBQUEsZUFBNkIsdUNBQ3pCO1VBQUE7SUFESjs7OztvQkNGRjtNQUFBO21DQUFBLFVBQUE7TUFBQTtJQUFBOzs7OyJ9
