/**
 * @fileoverview This file is generated by the Angular template compiler.
 * Do not edit.
 * @suppress {suspiciousCode,uselessCode,missingProperties,missingOverride}
 */
 /* tslint:disable */


import * as i0 from '@angular/core';
import * as i1 from '../../../../../node_modules/@angular-mdl/core/components/table/mdl-table.component.ngfactory';
import * as i2 from '@angular-mdl/core/components/shadow/mdl-shadow.directive';
import * as i3 from '@angular-mdl/core/components/table/mdl-table.component';
import * as i4 from './reservelist.component';
import * as i5 from './reserve.service';
const styles_ReserveListComponent:any[] = ([] as any[]);
export const RenderType_ReserveListComponent:i0.RendererType2 = i0.ɵcrt({encapsulation:2,
    styles:styles_ReserveListComponent,data:{}});
export function View_ReserveListComponent_0(_l:any):i0.ɵViewDefinition {
  return i0.ɵvid(0,[(_l()(),i0.ɵeld(0,(null as any),(null as any),2,'mdl-table',[['mdl-shadow',
      '2']],(null as any),(null as any),(null as any),i1.View_MdlTableComponent_0,
      i1.RenderType_MdlTableComponent)),i0.ɵdid(540672,(null as any),0,i2.MdlShadowDirective,
      [i0.ElementRef,i0.Renderer2],{mdlShadow:[0,'mdlShadow']},(null as any)),i0.ɵdid(49152,
      (null as any),0,i3.MdlTableComponent,([] as any[]),{model:[0,'model']},(null as any))],
      (_ck,_v) => {
        var _co:i4.ReserveListComponent = _v.component;
        const currVal_0:any = '2';
        _ck(_v,1,0,currVal_0);
        const currVal_1:any = _co.tableModel;
        _ck(_v,2,0,currVal_1);
      },(null as any));
}
export function View_ReserveListComponent_Host_0(_l:any):i0.ɵViewDefinition {
  return i0.ɵvid(0,[(_l()(),i0.ɵeld(0,(null as any),(null as any),1,'reserve-list',
      ([] as any[]),(null as any),(null as any),(null as any),View_ReserveListComponent_0,
      RenderType_ReserveListComponent)),i0.ɵdid(114688,(null as any),0,i4.ReserveListComponent,
      [i5.ReserveService],(null as any),(null as any))],(_ck,_v) => {
    _ck(_v,1,0);
  },(null as any));
}
export const ReserveListComponentNgFactory:i0.ComponentFactory<i4.ReserveListComponent> = i0.ɵccf('reserve-list',
    i4.ReserveListComponent,View_ReserveListComponent_Host_0,{},{},([] as any[]));
//# sourceMappingURL=data:application/json;base64,eyJmaWxlIjoiRDovcHJvZ3JhbS9BbXVtdS9saWIvY2hpbmFjaHUvcHJveHkvd2ViX21hdGVyaWFsL2FwcC9yZXNlcnZlbGlzdC5jb21wb25lbnQubmdmYWN0b3J5LnRzIiwidmVyc2lvbiI6Mywic291cmNlUm9vdCI6IiIsInNvdXJjZXMiOlsibmc6Ly8vRDovcHJvZ3JhbS9BbXVtdS9saWIvY2hpbmFjaHUvcHJveHkvd2ViX21hdGVyaWFsL2FwcC9yZXNlcnZlbGlzdC5jb21wb25lbnQudHMiLCJuZzovLy9EOi9wcm9ncmFtL0FtdW11L2xpYi9jaGluYWNodS9wcm94eS93ZWJfbWF0ZXJpYWwvYXBwL3Jlc2VydmVsaXN0LmNvbXBvbmVudC50cy5SZXNlcnZlTGlzdENvbXBvbmVudC5odG1sIiwibmc6Ly8vRDovcHJvZ3JhbS9BbXVtdS9saWIvY2hpbmFjaHUvcHJveHkvd2ViX21hdGVyaWFsL2FwcC9yZXNlcnZlbGlzdC5jb21wb25lbnQudHMuUmVzZXJ2ZUxpc3RDb21wb25lbnRfSG9zdC5odG1sIl0sInNvdXJjZXNDb250ZW50IjpbIiAiLCI8bWRsLXRhYmxlIG1kbC1zaGFkb3c9XCIyXCIgW3RhYmxlLW1vZGVsXT1cInRhYmxlTW9kZWxcIj4iLCI8cmVzZXJ2ZS1saXN0PjwvcmVzZXJ2ZS1saXN0PiJdLCJtYXBwaW5ncyI6IkFBQUE7Ozs7Ozs7Ozs7Ozs7Ozs7OztvQkNBQTtNQUFBO3FDQUFBLFVBQUE7TUFBQSwrRUFBQTtNQUFBOzs7UUFBVztRQUFYLFdBQVcsU0FBWDtRQUEwQjtRQUExQixXQUEwQixTQUExQjs7OztvQkNBQTtNQUFBO3FDQUFBLFVBQUE7TUFBQTtJQUFBOzs7OyJ9
