/**
 * @fileoverview This file is generated by the Angular template compiler.
 * Do not edit.
 * @suppress {suspiciousCode,uselessCode,missingProperties,missingOverride}
 */
 /* tslint:disable */


export const styles:any[] = ['.docs-navigation[_ngcontent-%COMP%]   .shucedule[_ngcontent-%COMP%] {\n    opacity: 1;\n    border-bottom-color: #18FFFF;\n}\n\n.channel_container[_ngcontent-%COMP%] {\n    float: left;\n}\n\n.channel_programs[_ngcontent-%COMP%]{\n    left: 0px;\n    position: relative;\n}\n\n.channel_program[_ngcontent-%COMP%] {\n    background-color: #eee;\n    border-right: 2px solid #ddd;\n    width: 176px;\n    position:absolute;\n}\n\n*[_ngcontent-%COMP%], [_ngcontent-%COMP%]:after, [_ngcontent-%COMP%]:before {\n    -webkit-box-sizing: border-box;\n    box-sizing: border-box;\n    margin: 0;\n    padding: 0;\n    word-wrap: break-word;\n}'];
//# sourceMappingURL=data:application/json;base64,eyJmaWxlIjoiRDovcHJvZ3JhbS9BbXVtdS9saWIvY2hpbmFjaHUvcHJveHkvd2ViX21hdGVyaWFsL2FwcC9zaHVjZWR1bGVkZXRhaWwuY29tcG9uZW50LmNzcy5zaGltLm5nc3R5bGUudHMiLCJ2ZXJzaW9uIjozLCJzb3VyY2VSb290IjoiIiwic291cmNlcyI6WyJuZzovLy9EOi9wcm9ncmFtL0FtdW11L2xpYi9jaGluYWNodS9wcm94eS93ZWJfbWF0ZXJpYWwvYXBwL3NodWNlZHVsZWRldGFpbC5jb21wb25lbnQuY3NzIl0sInNvdXJjZXNDb250ZW50IjpbIiAiXSwibWFwcGluZ3MiOiJBQUFBOzs7Ozs7OzsifQ==
