/**
 * @fileoverview This file is generated by the Angular template compiler.
 * Do not edit.
 * @suppress {suspiciousCode,uselessCode,missingProperties,missingOverride}
 */
 /* tslint:disable */


import * as i0 from './shuceduledetail.component.css.shim.ngstyle';
import * as i1 from '@angular/core';
import * as i2 from '@angular/common';
import * as i3 from './shuceduledetail.component';
import * as i4 from './carousel.component';
const styles_ShuceduleDetailComponent:any[] = [i0.styles];
export const RenderType_ShuceduleDetailComponent:i1.RendererType2 = i1.ɵcrt({encapsulation:0,
    styles:styles_ShuceduleDetailComponent,data:{}});
function View_ShuceduleDetailComponent_1(_l:any):i1.ɵViewDefinition {
  return i1.ɵvid(0,[(_l()(),i1.ɵeld(0,(null as any),(null as any),2,'div',[['class',
      'channel_program']],(null as any),(null as any),(null as any),(null as any),
      (null as any))),i1.ɵdid(278528,(null as any),0,i2.NgStyle,[i1.KeyValueDiffers,
      i1.ElementRef,i1.Renderer],{ngStyle:[0,'ngStyle']},(null as any)),(_l()(),i1.ɵted((null as any),
      ['\n      ','\n    ']))],(_ck,_v) => {
    var _co:any = _v.component;
    const currVal_0:any = _co.getStyle(_v.context.$implicit);
    _ck(_v,1,0,currVal_0);
  },(_ck,_v) => {
    const currVal_1:any = _v.context.$implicit.title;
    _ck(_v,2,0,currVal_1);
  });
}
export function View_ShuceduleDetailComponent_0(_l:any):i1.ɵViewDefinition {
  return i1.ɵvid(0,[(_l()(),i1.ɵeld(0,(null as any),(null as any),7,'div',[['class',
      'channel_container']],(null as any),(null as any),(null as any),(null as any),
      (null as any))),(_l()(),i1.ɵted((null as any),['\n  '])),(_l()(),i1.ɵeld(0,(null as any),
      (null as any),4,'div',[['class','channel_programs']],(null as any),(null as any),
      (null as any),(null as any),(null as any))),(_l()(),i1.ɵted((null as any),['\n    '])),
      (_l()(),i1.ɵand(16777216,(null as any),(null as any),1,(null as any),View_ShuceduleDetailComponent_1)),
      i1.ɵdid(802816,(null as any),0,i2.NgForOf,[i1.ViewContainerRef,i1.TemplateRef,
          i1.IterableDiffers],{ngForOf:[0,'ngForOf']},(null as any)),(_l()(),i1.ɵted((null as any),
          ['\n  '])),(_l()(),i1.ɵted((null as any),['\n']))],(_ck,_v) => {
    var _co:i3.ShuceduleDetailComponent = _v.component;
    const currVal_0:any = _co.channel.getPrograms(_co.date,(_co.date + 86400000));
    _ck(_v,5,0,currVal_0);
  },(null as any));
}
export function View_ShuceduleDetailComponent_Host_0(_l:any):i1.ɵViewDefinition {
  return i1.ɵvid(0,[(_l()(),i1.ɵeld(0,(null as any),(null as any),1,'shucedule-detail',
      ([] as any[]),[[2,'active',(null as any)]],(null as any),(null as any),View_ShuceduleDetailComponent_0,
      RenderType_ShuceduleDetailComponent)),i1.ɵdid(245760,(null as any),0,i3.ShuceduleDetailComponent,
      [i4.Carousel],(null as any),(null as any))],(_ck,_v) => {
    _ck(_v,1,0);
  },(_ck,_v) => {
    const currVal_0:any = i1.ɵnov(_v,1).active;
    _ck(_v,0,0,currVal_0);
  });
}
export const ShuceduleDetailComponentNgFactory:i1.ComponentFactory<i3.ShuceduleDetailComponent> = i1.ɵccf('shucedule-detail',
    i3.ShuceduleDetailComponent,View_ShuceduleDetailComponent_Host_0,{channel:'channel',
        time:'time',date:'date',index:'index',direction:'direction',active:'active'},
    {},([] as any[]));
//# sourceMappingURL=data:application/json;base64,eyJmaWxlIjoiRDovcHJvZ3JhbS9BbXVtdS9saWIvY2hpbmFjaHUvcHJveHkvd2ViX21hdGVyaWFsL2FwcC9zaHVjZWR1bGVkZXRhaWwuY29tcG9uZW50Lm5nZmFjdG9yeS50cyIsInZlcnNpb24iOjMsInNvdXJjZVJvb3QiOiIiLCJzb3VyY2VzIjpbIm5nOi8vL0Q6L3Byb2dyYW0vQW11bXUvbGliL2NoaW5hY2h1L3Byb3h5L3dlYl9tYXRlcmlhbC9hcHAvc2h1Y2VkdWxlZGV0YWlsLmNvbXBvbmVudC50cyIsIm5nOi8vL0Q6L3Byb2dyYW0vQW11bXUvbGliL2NoaW5hY2h1L3Byb3h5L3dlYl9tYXRlcmlhbC9hcHAvc2h1Y2VkdWxlZGV0YWlsLmNvbXBvbmVudC5odG1sIiwibmc6Ly8vRDovcHJvZ3JhbS9BbXVtdS9saWIvY2hpbmFjaHUvcHJveHkvd2ViX21hdGVyaWFsL2FwcC9zaHVjZWR1bGVkZXRhaWwuY29tcG9uZW50LnRzLlNodWNlZHVsZURldGFpbENvbXBvbmVudF9Ib3N0Lmh0bWwiXSwic291cmNlc0NvbnRlbnQiOlsiICIsIjxkaXYgY2xhc3M9XCJjaGFubmVsX2NvbnRhaW5lclwiPlxuICA8ZGl2IGNsYXNzPVwiY2hhbm5lbF9wcm9ncmFtc1wiPlxuICAgIDxkaXYgKm5nRm9yPVwibGV0IHByb2dyYW0gb2YgY2hhbm5lbC5nZXRQcm9ncmFtcyhkYXRlLGRhdGUrODY0MDAwMDApXCIgY2xhc3M9XCJjaGFubmVsX3Byb2dyYW1cIiBbbmdTdHlsZV09XCJnZXRTdHlsZShwcm9ncmFtKVwiPlxuICAgICAge3twcm9ncmFtLnRpdGxlfX1cbiAgICA8L2Rpdj5cbiAgPC9kaXY+XG48L2Rpdj4iLCI8c2h1Y2VkdWxlLWRldGFpbD48L3NodWNlZHVsZS1kZXRhaWw+Il0sIm1hcHBpbmdzIjoiQUFBQTs7Ozs7Ozs7Ozs7Ozs7Ozs7b0JDRUk7TUFBQTtNQUFBLHVCQUFBOytCQUFBLHlDQUEySDtNQUFBOztJQUE5QjtJQUE3RixXQUE2RixTQUE3Rjs7SUFBMkg7SUFBQTs7OztvQkFGL0g7TUFBQTtNQUFBLGdCQUErQix5Q0FDN0I7TUFBQTtNQUFBLDRDQUE4QjtNQUM1QjthQUFBOzRCQUFBLHlDQUVNO1VBQUEsV0FDRjs7SUFIQztJQUFMLFdBQUssU0FBTDs7OztvQkNGSjtNQUFBO3lDQUFBLFVBQUE7TUFBQTtJQUFBOztJQUFBO0lBQUEsV0FBQSxTQUFBOzs7Ozs7In0=
